language: node_js
node_js:
  - 6.9
before_install:
  - npm install -g grunt-cli
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - npm run qa
after_script:
  - codeclimate < test/coverage/*/lcov.info
